## NumPy ndarray介绍

In [1]:
import numpy as np

In [2]:
a=np.arange(0,20)

In [3]:
a.shape

(20,)

In [4]:
a=np.linspace(0,20)  

In [5]:
a.shape

(50,)

In [6]:
a=np.linspace(0,20,10)
a.shape

(10,)

In [7]:
a[::-1]

array([ 20.        ,  17.77777778,  15.55555556,  13.33333333,
        11.11111111,   8.88888889,   6.66666667,   4.44444444,
         2.22222222,   0.        ])

In [8]:
arr_1d = np.array([7, 2, 9, 10])
arr_1d

array([ 7,  2,  9, 10])

In [9]:
# m行n列
arr_2d = np.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
arr_2d

array([[ 5.2,  3. ,  4.5],
       [ 9.1,  0.1,  0.3]])

In [10]:
# k层m行n列
arr_3d = np.arange(24).reshape(4, 3, 2)
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

### 形状（shape）

##### 表示数组的维数或数组的大小

In [12]:
arr_3d.shape

(4, 3, 2)

In [17]:
arr_4d = np.arange(32).reshape(4,2,2,2)
arr_4d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]]])

In [18]:
arr_4d.shape

(4, 2, 2, 2)

### dtype

In [19]:
arr_1d.dtype

dtype('int64')

In [20]:
arr_1d_float32 = arr_1d.astype(np.float32)
arr_1d_float32

array([  7.,   2.,   9.,  10.], dtype=float32)

In [22]:
arr_1d_float64 = arr_1d.astype(np.float64)
arr_1d_float64

array([  7.,   2.,   9.,  10.])

In [24]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [25]:
arr_int = np.arange(10)
arr_int.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [26]:
arr_int.dtype

dtype('int64')

In [27]:
y=arr_int.astype(calibers.dtype)
y.dtype

dtype('float64')

### 索引和切片(basic indexing and slicing)

In [28]:
data = np.arange(5)*10
data

array([ 0, 10, 20, 30, 40])

In [29]:
data.shape

(5,)

In [30]:
data.dtype

dtype('int64')

In [31]:
b=data[1:-1]
b

array([10, 20, 30])

In [32]:
data[1:]

array([10, 20, 30, 40])

In [33]:
data = np.arange(24).reshape(2, 3, 4)
data

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
data[::2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [35]:
data[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [38]:
data[0:-1]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [39]:
data[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [40]:
data[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

#### 重点例子

In [41]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

##### 下面这是什么意思？

In [42]:
data[0][[1,0]]

array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

### 布尔/模板索引boolean/mask index

In [44]:
data = np.array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [3, 6, 9, 12],
       [4, 8, 12, 16]])
data

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [45]:
mask = data > 6
mask

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False,  True,  True,  True]], dtype=bool)

In [46]:
data[mask]

array([ 8,  9, 12,  8, 12, 16])

### 索引和切片的区别 

- 切片得到的是原多维数组的一个视图(view)，修改切片中的内容会导致原多维数组的内容也发生变化
- 布尔/模板索引产生新的数组

In [51]:
data = np.array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [3, 6, 9, 12],
       [4, 8, 12, 16]])
print(data)
print(data.shape)
data_slice = data[1:,1:3]
data_slice[:,1:2] = 0
print(data)
data_copy = data[1:,1:3].copy()
data_copy[...] = 1
print(data_copy)
print(data)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
(4, 4)
[[ 1  2  3  4]
 [ 2  4  0  8]
 [ 3  6  0 12]
 [ 4  8  0 16]]
[[1 1]
 [1 1]
 [1 1]]
[[ 1  2  3  4]
 [ 2  4  0  8]
 [ 3  6  0 12]
 [ 4  8  0 16]]


### 常用函数

In [52]:
arr_ones = np.ones((3,3))
arr_ones

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [53]:
arr_zeros = np.zeros((3,3))
arr_zeros

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [54]:
arr_eye = np.eye(3,dtype=np.int64)
arr_eye

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [55]:
e = np.eye(3)
e

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [56]:
e.dtype

dtype('float64')

In [57]:
arr_empty = np.empty((3,4))

In [58]:
arr_full = np.full((3, 3), 10)

In [59]:
arr_empty

array([[  4.65615364e-310,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000]])

In [60]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
np.linspace(0,10)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [62]:
3+3*np.random.randn(3,3)

array([[-0.73869838,  8.48168423,  5.19053221],
       [-0.91190986,  5.12248399,  1.21236292],
       [-0.52909441,  2.49903491,  3.82587558]])

### 常用统计函数(如sum，mean，std，var，min，max)

In [63]:
data = np.arange(24).reshape(2, 3, 4)
data.shape

(2, 3, 4)

In [64]:
data.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [65]:
print(data.sum(axis=0))
print(np.sum(data, axis=1))
print(np.sum(data, axis=(0,1)))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[60 66 72 78]


In [66]:
print(data.std())
print(np.std(data))
print(data.var())
print(data.min(axis=1))

6.92218655243
6.92218655243
47.9166666667
[[ 0  1  2  3]
 [12 13 14 15]]


#### numpy中互相关correlate，协方差cov与相关系数corrcoef的使用

In [67]:
np.correlate([1, 2, 3], [0, 1, 0.5])

array([ 3.5])

### 常用数学函数(如sin，cos，exp，sqrt，fabs)

In [68]:
np.sqrt(9)

3.0

In [69]:
np.fabs(-3)

3.0

In [70]:
np.exp(2)

7.3890560989306504

##### 下面语句的含义

In [71]:
vector1 = np.array([1,1,1])
vector2 = np.array([2,3,6])
res=np.linalg.norm(vector1-vector2)
res

5.4772255750516612

### reshape()

In [72]:
import numpy as np
Z = np.zeros((4, 4), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [73]:
data = np.arange(16).reshape(4, 4)

In [74]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
data[:,[3,1,2,0]]

array([[ 3,  1,  2,  0],
       [ 7,  5,  6,  4],
       [11,  9, 10,  8],
       [15, 13, 14, 12]])

### numpy数组广播(broadcasting)

#### 重点例子

In [76]:
a = np.arange(5)
b = a[:, np.newaxis]
c = np.arange(8)
d = b+c

In [77]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  5,  6,  7,  8,  9, 10, 11]])

### python基础

In [78]:
a=3
a**2

9

In [79]:
print('He said \"I\'m hungry.\"')

He said "I'm hungry."


In [80]:
a=complex(2, -8)
a

(2-8j)

python中
- return语句
- 类的构造函数